version: '3.8'

services:
  postgres-dev:
    image: postgres:14
    container_name: whaticket-dev-postgres
    environment:
      - POSTGRES_DB=whaticket_dev
      - POSTGRES_USER=whaticket_dev
      - POSTGRES_PASSWORD=whaticket_dev
    ports:
      - "5434:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  redis-dev:
    image: redis:7
    container_name: whaticket-dev-redis
    ports:
      - "6380:6379"
    volumes:
      - redisdata_dev:/data

volumes:
  pgdata_dev:
  redisdata_dev:
