version: "3.8"

# ARQUIVO APENAS PARA CONSTRUIR AS IMAGENS NO SERVIDOR
# Use: docker compose -f deploy/docker-compose.build.yml build

services:
  whaticket_backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: whaticket-backend:latest

  whaticket_frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=https://homologapi.whatsflux.com.br
    image: whaticket-frontend:latest
